[project]
name = "D47crunch"
version = "3.0.0a1"
description = "Standardization and analytical error propagation of Δ47 and Δ48 clumped-isotope measurements"
readme = "readme.md"
license = "MIT"
classifiers = ["License :: OSI Approved :: MIT License"]
authors = [
	{ name = "Mathieu Daëron",  email = "mathieu@daeron.fr" },
]
requires-python = ">= 3.12"
dependencies = [
    "numpy >=1.21",
    "scipy >=1.7.0",
    "matplotlib >=3.4.2",
    "lmfit >=1.0.2",
    "typer >=0.17",
    "rich",
    "typing-extensions>=4.15.0",
    "pymc>=6.0",
    "coloraide>=8.10",
    "sympy>=1.14.0",
]

[project.urls]
Home = "https://github.com/mdaeron/D47crunch"
Documentation = "https://mdaeron.github.io/D47crunch"

[project.scripts]
D47crunch = "D47crunch:__cli"

[build-system]
requires = ["uv_build>=0.9.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "D47crunch"

[dependency-groups]
dev = [
	"pdoc>=16.0.0",
	"pytest>=9.0.2",
]
